name: ci

on: [pull_request]

jobs:
  gqlnode-server-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/gqlnode/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Build
        run: npm install

      - name: Test
        run: npm test
  reactnode-client-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/reactnode/react/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Build
        run: npm install

      - name: Test
        run: npm test
  reactnode-server-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/reactnode/node/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Build
        run: npm install

      - name: Test
        run: npm test
