name: ci

on: [pull_request]

jobs:
  gqlnode-server-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /gqlnode/react/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Build
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
  reactnode-client-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /reactnode/react/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Build
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
  reactnode-server-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /reactnode/node/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Build
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
